name: 'brightwheel'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  brightwheel:
    # Applies to all files under models/example/
    staging:
      materialized: view
      schema: staging
    
    intermediate:
      materialized: view
      schema: intermediate
    
    mart:
      materialized: table
      schema: mart
